USE PRODUCTOS_APP;
GO

SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

/*
  DIAGNOSTICO PREVIO A LIMPIEZA
  -----------------------------
  Este script es 100% de solo lectura:
  - no ejecuta DELETE, UPDATE, TRUNCATE ni DBCC RESEED;
  - identifica el volumen transaccional y el catálogo PRODUCTOS;
  - permite revisar el alcance antes de autorizar la limpieza.
*/

PRINT '============================================================';
PRINT ' DIAGNOSTICO DE DATOS DE PRUEBA - PRODUCTOS_APP';
PRINT ' SOLO LECTURA: NO SE MODIFICARA NINGUN REGISTRO';
PRINT '============================================================';

DECLARE @EsperadosProductosPrueba int = 15;

CREATE TABLE #Conteos (
    ORDEN int NOT NULL,
    TABLA sysname NOT NULL,
    REGISTROS bigint NOT NULL
);

IF OBJECT_ID('dbo.ALTAS_PRODUCTOS', 'U') IS NOT NULL
    INSERT #Conteos SELECT 10, 'ALTAS_PRODUCTOS', COUNT_BIG(*) FROM dbo.ALTAS_PRODUCTOS;

IF OBJECT_ID('dbo.ALTAS_PRODUCTOS_DETALLE', 'U') IS NOT NULL
    INSERT #Conteos SELECT 20, 'ALTAS_PRODUCTOS_DETALLE', COUNT_BIG(*) FROM dbo.ALTAS_PRODUCTOS_DETALLE;

IF OBJECT_ID('dbo.ALTAS_PRODUCTOS_FAMILIAS_DETALLE', 'U') IS NOT NULL
    INSERT #Conteos SELECT 30, 'ALTAS_PRODUCTOS_FAMILIAS_DETALLE', COUNT_BIG(*) FROM dbo.ALTAS_PRODUCTOS_FAMILIAS_DETALLE;

IF OBJECT_ID('dbo.ALTAS_PRODUCTOS_EXPORTADOS', 'U') IS NOT NULL
    INSERT #Conteos SELECT 40, 'ALTAS_PRODUCTOS_EXPORTADOS', COUNT_BIG(*) FROM dbo.ALTAS_PRODUCTOS_EXPORTADOS;

IF OBJECT_ID('dbo.PEDIDOS', 'U') IS NOT NULL
    INSERT #Conteos SELECT 50, 'PEDIDOS', COUNT_BIG(*) FROM dbo.PEDIDOS;

IF OBJECT_ID('dbo.PEDIDOS_DETALLE', 'U') IS NOT NULL
    INSERT #Conteos SELECT 60, 'PEDIDOS_DETALLE', COUNT_BIG(*) FROM dbo.PEDIDOS_DETALLE;

IF OBJECT_ID('dbo.PEDIDOS_EXPORTACIONES', 'U') IS NOT NULL
    INSERT #Conteos SELECT 70, 'PEDIDOS_EXPORTACIONES', COUNT_BIG(*) FROM dbo.PEDIDOS_EXPORTACIONES;

IF OBJECT_ID('dbo.PRODUCTOS', 'U') IS NOT NULL
    INSERT #Conteos SELECT 80, 'PRODUCTOS', COUNT_BIG(*) FROM dbo.PRODUCTOS;

SELECT TABLA, REGISTROS
FROM #Conteos
ORDER BY ORDEN;

PRINT '';
PRINT 'CONTROL DE LOS 15 PRODUCTOS DE PRUEBA';

IF OBJECT_ID('dbo.PRODUCTOS', 'U') IS NOT NULL
BEGIN
    DECLARE @CantidadProductos bigint = (SELECT COUNT_BIG(*) FROM dbo.PRODUCTOS);

    SELECT
        @EsperadosProductosPrueba AS PRODUCTOS_ESPERADOS,
        @CantidadProductos AS PRODUCTOS_ENCONTRADOS,
        CASE
            WHEN @CantidadProductos = @EsperadosProductosPrueba THEN 'COINCIDE'
            ELSE 'REVISAR_ANTES_DE_LIMPIAR'
        END AS RESULTADO;

    SELECT TOP (100) *
    FROM dbo.PRODUCTOS
    ORDER BY 1;
END;

PRINT '';
PRINT 'RESUMEN DE ALTAS POR EMPRESA Y ESTADO';

IF OBJECT_ID('dbo.ALTAS_PRODUCTOS', 'U') IS NOT NULL
BEGIN
    SELECT
        ID_EMPRESA,
        ESTADO,
        COUNT_BIG(*) AS ALTAS
    FROM dbo.ALTAS_PRODUCTOS
    GROUP BY ID_EMPRESA, ESTADO
    ORDER BY ID_EMPRESA, ESTADO;

    SELECT
        A.ID_EMPRESA,
        A.ID_ALTA,
        A.CODIGO_ALTA,
        A.DETALLE_MARCA,
        A.DETALLE_RUBRO,
        A.ESTADO,
        COUNT_BIG(D.ID_DETALLE) AS DETALLES
    FROM dbo.ALTAS_PRODUCTOS A
    LEFT JOIN dbo.ALTAS_PRODUCTOS_DETALLE D
        ON D.ID_ALTA = A.ID_ALTA
       AND D.ID_EMPRESA = A.ID_EMPRESA
    GROUP BY
        A.ID_EMPRESA, A.ID_ALTA, A.CODIGO_ALTA,
        A.DETALLE_MARCA, A.DETALLE_RUBRO, A.ESTADO
    ORDER BY A.ID_EMPRESA, A.ID_ALTA;
END;

PRINT '';
PRINT 'RESUMEN DE PEDIDOS POR EMPRESA Y ESTADO';

IF OBJECT_ID('dbo.PEDIDOS', 'U') IS NOT NULL
BEGIN
    SELECT
        ID_EMPRESA,
        ESTADO,
        COUNT_BIG(*) AS PEDIDOS
    FROM dbo.PEDIDOS
    GROUP BY ID_EMPRESA, ESTADO
    ORDER BY ID_EMPRESA, ESTADO;

    SELECT
        P.ID_EMPRESA,
        P.ID_PEDIDO,
        P.CODIGO_PEDIDO,
        P.ID_ALTA,
        P.ESTADO,
        COUNT_BIG(D.ID_PEDIDO_DETALLE) AS DETALLES,
        COALESCE(SUM(D.CANTIDAD_PARES), 0) AS PARES
    FROM dbo.PEDIDOS P
    LEFT JOIN dbo.PEDIDOS_DETALLE D
        ON D.ID_PEDIDO = P.ID_PEDIDO
       AND D.ID_EMPRESA = P.ID_EMPRESA
    GROUP BY
        P.ID_EMPRESA, P.ID_PEDIDO, P.CODIGO_PEDIDO,
        P.ID_ALTA, P.ESTADO
    ORDER BY P.ID_EMPRESA, P.ID_PEDIDO;
END;

PRINT '';
PRINT 'CLAVES FORANEAS RELACIONADAS';

SELECT
    OBJECT_SCHEMA_NAME(FK.parent_object_id) + '.' + OBJECT_NAME(FK.parent_object_id) AS TABLA_HIJA,
    FK.name AS CLAVE_FORANEA,
    OBJECT_SCHEMA_NAME(FK.referenced_object_id) + '.' + OBJECT_NAME(FK.referenced_object_id) AS TABLA_PADRE,
    FK.delete_referential_action_desc AS ACCION_DELETE
FROM sys.foreign_keys FK
WHERE OBJECT_NAME(FK.parent_object_id) IN (
        'ALTAS_PRODUCTOS', 'ALTAS_PRODUCTOS_DETALLE',
        'ALTAS_PRODUCTOS_FAMILIAS_DETALLE', 'ALTAS_PRODUCTOS_EXPORTADOS',
        'PEDIDOS', 'PEDIDOS_DETALLE', 'PEDIDOS_EXPORTACIONES', 'PRODUCTOS'
    )
   OR OBJECT_NAME(FK.referenced_object_id) IN (
        'ALTAS_PRODUCTOS', 'ALTAS_PRODUCTOS_DETALLE',
        'ALTAS_PRODUCTOS_FAMILIAS_DETALLE', 'ALTAS_PRODUCTOS_EXPORTADOS',
        'PEDIDOS', 'PEDIDOS_DETALLE', 'PEDIDOS_EXPORTACIONES', 'PRODUCTOS'
    )
ORDER BY TABLA_PADRE, TABLA_HIJA, CLAVE_FORANEA;

DROP TABLE #Conteos;

PRINT '';
PRINT 'DIAGNOSTICO FINALIZADO. NO SE MODIFICO NINGUN DATO.';
GO
