USE [PRODUCTOS_APP];
GO

SET XACT_ABORT ON;
GO

BEGIN TRY
    BEGIN TRANSACTION;

    IF OBJECT_ID('dbo.MAESTRO_PROVEEDORES', 'U') IS NULL
    BEGIN
        CREATE TABLE dbo.MAESTRO_PROVEEDORES
        (
            CODIGO              varchar(30)  NOT NULL,
            PRESEA              varchar(30)  NULL,
            RUBRO               varchar(100) NULL,
            NVA_RAZON_SOCIAL    varchar(200) NOT NULL,
            ACTIVO              bit          NOT NULL
                CONSTRAINT DF_MAESTRO_PROVEEDORES_ACTIVO DEFAULT (1),
            FECHA_SINCRONIZACION datetime2(0) NOT NULL
                CONSTRAINT DF_MAESTRO_PROVEEDORES_FECHA DEFAULT (SYSDATETIME()),

            CONSTRAINT PK_MAESTRO_PROVEEDORES
                PRIMARY KEY (CODIGO)
        );
    END;

    IF COL_LENGTH('dbo.ALTAS_PRODUCTOS_DETALLE', 'CODIGO_PROVEEDOR') IS NULL
        ALTER TABLE dbo.ALTAS_PRODUCTOS_DETALLE
        ADD CODIGO_PROVEEDOR varchar(30) NULL;

    IF COL_LENGTH('dbo.ALTAS_PRODUCTOS_DETALLE', 'PRESEA_PROVEEDOR') IS NULL
        ALTER TABLE dbo.ALTAS_PRODUCTOS_DETALLE
        ADD PRESEA_PROVEEDOR varchar(30) NULL;

    IF COL_LENGTH('dbo.ALTAS_PRODUCTOS_DETALLE', 'RUBRO_PROVEEDOR') IS NULL
        ALTER TABLE dbo.ALTAS_PRODUCTOS_DETALLE
        ADD RUBRO_PROVEEDOR varchar(100) NULL;

    IF COL_LENGTH('dbo.ALTAS_PRODUCTOS_DETALLE', 'DETALLE_PROVEEDOR') IS NULL
        ALTER TABLE dbo.ALTAS_PRODUCTOS_DETALLE
        ADD DETALLE_PROVEEDOR varchar(200) NULL;

    COMMIT TRANSACTION;

    PRINT 'Proveedor: estructura creada correctamente.';
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    THROW;
END CATCH;
GO
