IF OBJECT_ID('dbo.PEDIDOS_EXPORTACIONES', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PEDIDOS_EXPORTACIONES
    (
        ID_EXPORTACION BIGINT IDENTITY(1,1) NOT NULL,
        ID_PEDIDO BIGINT NOT NULL,
        TIPO_EXPORTACION VARCHAR(30) NOT NULL,
        NOMBRE_ARCHIVO VARCHAR(255) NOT NULL,
        FECHA_EXPORTACION DATETIME2(0) NOT NULL
            CONSTRAINT DF_PEDIDOS_EXPORTACIONES_FECHA DEFAULT SYSDATETIME(),
        USUARIO_EXPORTACION VARCHAR(100) NULL,
        CANTIDAD_REGISTROS INT NULL,
        ESTADO VARCHAR(20) NOT NULL
            CONSTRAINT DF_PEDIDOS_EXPORTACIONES_ESTADO DEFAULT ('OK'),
        OBSERVACIONES VARCHAR(500) NULL,

        CONSTRAINT PK_PEDIDOS_EXPORTACIONES
            PRIMARY KEY (ID_EXPORTACION),

        CONSTRAINT FK_PEDIDOS_EXPORTACIONES_PEDIDOS
            FOREIGN KEY (ID_PEDIDO)
            REFERENCES dbo.PEDIDOS(ID_PEDIDO),

        CONSTRAINT CK_PEDIDOS_EXPORTACIONES_TIPO
            CHECK (TIPO_EXPORTACION IN ('PEDIDO_EXCEL','MASTER_DATA_APP','PREC_FOB')),

        CONSTRAINT CK_PEDIDOS_EXPORTACIONES_ESTADO
            CHECK (ESTADO IN ('OK','ERROR'))
    );

    CREATE INDEX IX_PEDIDOS_EXPORTACIONES_PEDIDO_FECHA
        ON dbo.PEDIDOS_EXPORTACIONES(ID_PEDIDO, FECHA_EXPORTACION DESC);
END;
