/* ============================================================
   PASO 3K26 - ACTIVAR DESTINOS DE PEDIDOS

   VICBOR / ATOMIK     -> PEDIDOS\VICBOR
   MIDING / MONTAGNE   -> PEDIDOS\MIDING\MONTAGNE
   MIDING / 47 STREET  -> PEDIDOS\MIDING\47\_STREET

   Los tres tipos de archivo usan la carpeta de su empresa.
   KEVINGSTON no se modifica.
   ============================================================ */

SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    UPDATE C
    SET
        C.RUTA_PEDIDO_EXCEL = 'PEDIDOS\VICBOR',
        C.RUTA_MASTER_DATA_APP = 'PEDIDOS\VICBOR',
        C.RUTA_PREC_FOB = 'PEDIDOS\VICBOR',
        C.ACTIVA = 1,
        C.FECHA_ACTUALIZACION = SYSDATETIME()
    FROM dbo.PEDIDOS_EXPORT_CONFIG C
    INNER JOIN dbo.EMPRESAS_MARCAS EM
        ON EM.ID_EMPRESA_MARCA = C.ID_EMPRESA_MARCA
    INNER JOIN dbo.EMPRESAS E
        ON E.ID_EMPRESA = EM.ID_EMPRESA
    INNER JOIN dbo.MAESTRO_MARCAS MM
        ON MM.ID_EMPRESA = EM.ID_EMPRESA
       AND MM.CODIGO_MARCA = EM.CODIGO_MARCA
    WHERE UPPER(LTRIM(RTRIM(E.RAZON_SOCIAL))) = 'VICBOR'
      AND UPPER(LTRIM(RTRIM(MM.DETALLE_MARCA))) = 'ATOMIK';

    IF @@ROWCOUNT <> 1
        THROW 51001, 'No se encontró una única configuración para VICBOR / ATOMIK.', 1;

    UPDATE C
    SET
        C.RUTA_PEDIDO_EXCEL = 'PEDIDOS\MIDING\MONTAGNE',
        C.RUTA_MASTER_DATA_APP = 'PEDIDOS\MIDING\MONTAGNE',
        C.RUTA_PREC_FOB = 'PEDIDOS\MIDING\MONTAGNE',
        C.ACTIVA = 1,
        C.FECHA_ACTUALIZACION = SYSDATETIME()
    FROM dbo.PEDIDOS_EXPORT_CONFIG C
    INNER JOIN dbo.EMPRESAS_MARCAS EM
        ON EM.ID_EMPRESA_MARCA = C.ID_EMPRESA_MARCA
    INNER JOIN dbo.EMPRESAS E
        ON E.ID_EMPRESA = EM.ID_EMPRESA
    INNER JOIN dbo.MAESTRO_MARCAS MM
        ON MM.ID_EMPRESA = EM.ID_EMPRESA
       AND MM.CODIGO_MARCA = EM.CODIGO_MARCA
    WHERE UPPER(LTRIM(RTRIM(E.RAZON_SOCIAL))) = 'MIDING'
      AND UPPER(LTRIM(RTRIM(MM.DETALLE_MARCA))) = 'MONTAGNE';

    IF @@ROWCOUNT <> 1
        THROW 51002, 'No se encontró una única configuración para MIDING / MONTAGNE.', 1;

    UPDATE C
    SET
        C.RUTA_PEDIDO_EXCEL = 'PEDIDOS\MIDING\47\_STREET',
        C.RUTA_MASTER_DATA_APP = 'PEDIDOS\MIDING\47\_STREET',
        C.RUTA_PREC_FOB = 'PEDIDOS\MIDING\47\_STREET',
        C.ACTIVA = 1,
        C.FECHA_ACTUALIZACION = SYSDATETIME()
    FROM dbo.PEDIDOS_EXPORT_CONFIG C
    INNER JOIN dbo.EMPRESAS_MARCAS EM
        ON EM.ID_EMPRESA_MARCA = C.ID_EMPRESA_MARCA
    INNER JOIN dbo.EMPRESAS E
        ON E.ID_EMPRESA = EM.ID_EMPRESA
    INNER JOIN dbo.MAESTRO_MARCAS MM
        ON MM.ID_EMPRESA = EM.ID_EMPRESA
       AND MM.CODIGO_MARCA = EM.CODIGO_MARCA
    WHERE UPPER(LTRIM(RTRIM(E.RAZON_SOCIAL))) = 'MIDING'
      AND UPPER(LTRIM(RTRIM(MM.DETALLE_MARCA))) = '47 STREET';

    IF @@ROWCOUNT <> 1
        THROW 51003, 'No se encontró una única configuración para MIDING / 47 STREET.', 1;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;

SELECT
    E.RAZON_SOCIAL,
    MM.DETALLE_MARCA,
    EM.CODIGO_MARCA,
    C.RUTA_PEDIDO_EXCEL,
    C.RUTA_MASTER_DATA_APP,
    C.RUTA_PREC_FOB,
    C.ACTIVA
FROM dbo.PEDIDOS_EXPORT_CONFIG C
INNER JOIN dbo.EMPRESAS_MARCAS EM
    ON EM.ID_EMPRESA_MARCA = C.ID_EMPRESA_MARCA
INNER JOIN dbo.EMPRESAS E
    ON E.ID_EMPRESA = EM.ID_EMPRESA
LEFT JOIN dbo.MAESTRO_MARCAS MM
    ON MM.ID_EMPRESA = EM.ID_EMPRESA
   AND MM.CODIGO_MARCA = EM.CODIGO_MARCA
WHERE
    (E.RAZON_SOCIAL = 'VICBOR' AND MM.DETALLE_MARCA = 'ATOMIK')
    OR
    (E.RAZON_SOCIAL = 'MIDING' AND MM.DETALLE_MARCA = 'MONTAGNE')
    OR
    (E.RAZON_SOCIAL = 'MIDING' AND MM.DETALLE_MARCA = '47 STREET')
ORDER BY E.ID_EMPRESA;
