USE PRODUCTOS_APP;
GO

SET XACT_ABORT ON;
GO

/*
  Información adicional capturada al generar una familia de productos.
  La migración es idempotente: puede ejecutarse más de una vez.
*/
BEGIN TRY
    BEGIN TRANSACTION;

    IF COL_LENGTH('dbo.ALTAS_PRODUCTOS_DETALLE', 'CO_NEW') IS NULL
        ALTER TABLE dbo.ALTAS_PRODUCTOS_DETALLE ADD CO_NEW NVARCHAR(50) NULL;

    IF COL_LENGTH('dbo.ALTAS_PRODUCTOS_DETALLE', 'MUESTRA') IS NULL
        ALTER TABLE dbo.ALTAS_PRODUCTOS_DETALLE ADD MUESTRA NVARCHAR(50) NULL;

    IF COL_LENGTH('dbo.ALTAS_PRODUCTOS_DETALLE', 'COMENTARIO') IS NULL
        ALTER TABLE dbo.ALTAS_PRODUCTOS_DETALLE ADD COMENTARIO NVARCHAR(255) NULL;

    IF COL_LENGTH('dbo.ALTAS_PRODUCTOS_DETALLE', 'CORRECCIONES') IS NULL
        ALTER TABLE dbo.ALTAS_PRODUCTOS_DETALLE ADD CORRECCIONES NVARCHAR(255) NULL;

    IF COL_LENGTH('dbo.ALTAS_PRODUCTOS_DETALLE', 'MATERIAL_CALZADO') IS NULL
        ALTER TABLE dbo.ALTAS_PRODUCTOS_DETALLE ADD MATERIAL_CALZADO NVARCHAR(100) NULL;

    IF COL_LENGTH('dbo.ALTAS_PRODUCTOS_DETALLE', 'MATERIAL_SUELA') IS NULL
        ALTER TABLE dbo.ALTAS_PRODUCTOS_DETALLE ADD MATERIAL_SUELA NVARCHAR(100) NULL;

    IF COL_LENGTH('dbo.ALTAS_PRODUCTOS_DETALLE', 'TIPO_AJUSTE') IS NULL
        ALTER TABLE dbo.ALTAS_PRODUCTOS_DETALLE ADD TIPO_AJUSTE NVARCHAR(100) NULL;

    IF COL_LENGTH('dbo.ALTAS_PRODUCTOS_DETALLE', 'DESCRIPCION') IS NULL
        ALTER TABLE dbo.ALTAS_PRODUCTOS_DETALLE ADD DESCRIPCION NVARCHAR(500) NULL;

    IF COL_LENGTH('dbo.ALTAS_PRODUCTOS_DETALLE', 'FLOW') IS NULL
        ALTER TABLE dbo.ALTAS_PRODUCTOS_DETALLE ADD FLOW NVARCHAR(100) NULL;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO

SELECT
    C.name AS CAMPO,
    T.name AS TIPO,
    CASE
        WHEN T.name IN ('nvarchar', 'nchar') THEN C.max_length / 2
        ELSE C.max_length
    END AS LARGO,
    C.is_nullable AS ADMITE_NULL
FROM sys.columns C
INNER JOIN sys.types T
    ON T.user_type_id = C.user_type_id
WHERE C.object_id = OBJECT_ID('dbo.ALTAS_PRODUCTOS_DETALLE')
  AND C.name IN (
      'CO_NEW', 'MUESTRA', 'COMENTARIO', 'CORRECCIONES',
      'MATERIAL_CALZADO', 'MATERIAL_SUELA', 'TIPO_AJUSTE',
      'DESCRIPCION', 'FLOW'
  )
ORDER BY C.column_id;
GO
