/* ============================================================
   DIAGNOSTICO POST-IMPORTACION - INDUSTRIAS GYD

   Solo lectura. Muestra cantidades de maestros e identifica
   las curvas cuya suma por talle no coincide con PARES.
   ============================================================ */

SET NOCOUNT ON;

DECLARE @ID_EMPRESA INT =
(
    SELECT ID_EMPRESA
    FROM dbo.EMPRESAS
    WHERE CODIGO_EMPRESA = '70000'
);

IF @ID_EMPRESA IS NULL
    THROW 51050, 'No se encontró la empresa 70000.', 1;

SELECT 'MAESTRO_ANOS' AS TABLA, COUNT_BIG(*) AS REGISTROS
FROM dbo.MAESTRO_ANOS WHERE ID_EMPRESA = @ID_EMPRESA AND ACTIVO = 1
UNION ALL
SELECT 'MAESTRO_COLORES', COUNT_BIG(*)
FROM dbo.MAESTRO_COLORES WHERE ID_EMPRESA = @ID_EMPRESA AND ACTIVO = 1
UNION ALL
SELECT 'MAESTRO_CLASIFICACION', COUNT_BIG(*)
FROM dbo.MAESTRO_CLASIFICACION WHERE ID_EMPRESA = @ID_EMPRESA AND ACTIVO = 1
UNION ALL
SELECT 'MAESTRO_MARCAS', COUNT_BIG(*)
FROM dbo.MAESTRO_MARCAS WHERE ID_EMPRESA = @ID_EMPRESA AND ACTIVO = 1
UNION ALL
SELECT 'MAESTRO_MODELOS', COUNT_BIG(*)
FROM dbo.MAESTRO_MODELOS WHERE ID_EMPRESA = @ID_EMPRESA AND ACTIVO = 1
UNION ALL
SELECT 'MAESTRO_RUBROS', COUNT_BIG(*)
FROM dbo.MAESTRO_RUBROS WHERE ID_EMPRESA = @ID_EMPRESA AND ACTIVO = 1
UNION ALL
SELECT 'MAESTRO_RUBRO_FACT', COUNT_BIG(*)
FROM dbo.MAESTRO_RUBRO_FACT WHERE ID_EMPRESA = @ID_EMPRESA AND ACTIVO = 1
UNION ALL
SELECT 'MAESTRO_TALLES', COUNT_BIG(*)
FROM dbo.MAESTRO_TALLES WHERE ID_EMPRESA = @ID_EMPRESA AND ACTIVO = 1
UNION ALL
SELECT 'MAESTRO_TALLES_MODULOS', COUNT_BIG(*)
FROM dbo.MAESTRO_TALLES_MODULOS WHERE ID_EMPRESA = @ID_EMPRESA AND ACTIVO = 1
ORDER BY TABLA;

SELECT
    CODIGO_MODULO,
    DETALLE_MODULO,
    PARES,
    TOTAL_CALCULADO,
    OBSERVACION
FROM dbo.MAESTRO_TALLES_MODULOS
WHERE ID_EMPRESA = @ID_EMPRESA
  AND ACTIVO = 1
  AND ES_CONSISTENTE = 0
ORDER BY CODIGO_MODULO;
