/* ============================================================
   ALTA DE EMPRESA - BAGUNZA

   Empresa: 15000 / BAGUNZA
   Marca  : 160 / BAGUNZA
   Rubros : todos los rubros conocidos

   IMPORTANTE:
   - Requiere 07_ampliar_codigo_marca_a_5.sql.
   - Configura maestros, Altas y Pedidos.
   - Es transaccional e idempotente.
   - Puede ejecutarse nuevamente para corregir la configuración.
   ============================================================ */

SET NOCOUNT ON;
SET XACT_ABORT ON;

DECLARE @CODIGO_EMPRESA VARCHAR(20) = '15000';
DECLARE @RAZON_SOCIAL VARCHAR(150) = 'BAGUNZA';
DECLARE @FTP_RUTA_MAESTROS VARCHAR(255) = '/PRODUCTOS/MAESTRO_BAGUNZA';
DECLARE @FTP_ARCHIVO_PRODUCTOS VARCHAR(150) = 'TBL_MAESTRO_PRODS_BAGUNZA.TXT';
DECLARE @ACTIVAR BIT = 1;
DECLARE @ID_EMPRESA INT;

DECLARE @MARCAS TABLE
(
    CODIGO_MARCA VARCHAR(5) NOT NULL PRIMARY KEY,
    DETALLE_MARCA VARCHAR(20) NOT NULL,
    FTP_RUTA_ALTAS VARCHAR(255) NOT NULL,
    FTP_ARCHIVO_PRODUCTOS VARCHAR(150) NOT NULL,
    FTP_ARCHIVO_MODELOS VARCHAR(150) NOT NULL,
    FTP_ARCHIVO_PRIMERAS_SEGUNDAS VARCHAR(150) NOT NULL,
    FTP_ARCHIVO_RELFORMU VARCHAR(150) NOT NULL,
    FTP_ARCHIVO_RELACION VARCHAR(150) NOT NULL,
    RUTA_PEDIDO_EXCEL VARCHAR(500) NOT NULL,
    RUTA_MASTER_DATA_APP VARCHAR(500) NOT NULL,
    RUTA_PREC_FOB VARCHAR(500) NOT NULL
);

INSERT INTO @MARCAS
(
    CODIGO_MARCA,
    DETALLE_MARCA,
    FTP_RUTA_ALTAS,
    FTP_ARCHIVO_PRODUCTOS,
    FTP_ARCHIVO_MODELOS,
    FTP_ARCHIVO_PRIMERAS_SEGUNDAS,
    FTP_ARCHIVO_RELFORMU,
    FTP_ARCHIVO_RELACION,
    RUTA_PEDIDO_EXCEL,
    RUTA_MASTER_DATA_APP,
    RUTA_PREC_FOB
)
VALUES
(
    '160',
    'BAGUNZA',
    'ALTAS_PRODUCTOS\BAGUNZA',
    'ALTAS_PRODUCTOS.DBI',
    'MODELOS_BAGUNZA_TBL_PRODBASE.DBI',
    'PRIMERAS_SEGUNDAS_BAGUNZA.DBI',
    'PRODUCTOS_RELFORMU.DBI',
    'PRODUCTOS_RELACION.DBI',
    'PEDIDOS\BAGUNZA',
    'PEDIDOS\BAGUNZA',
    'PEDIDOS\BAGUNZA'
);

DECLARE @RUBROS TABLE
(
    CODIGO_RUBRO VARCHAR(1) NOT NULL PRIMARY KEY,
    DETALLE_RUBRO VARCHAR(30) NOT NULL
);

INSERT INTO @RUBROS (CODIGO_RUBRO, DETALLE_RUBRO)
VALUES
    ('0', 'VARIOS'),
    ('1', 'CALZADO'),
    ('2', 'INDUMENTARIA'),
    ('3', 'ACCESORIOS'),
    ('4', 'LICENCIAS'),
    ('5', 'POP'),
    ('8', 'PROMOCIONES Y AFINES'),
    ('9', 'SIN RUBRO');

BEGIN TRY
    BEGIN TRANSACTION;

    IF COL_LENGTH('dbo.MAESTRO_MARCAS', 'CODIGO_MARCA') < 5
        THROW 51030, 'CODIGO_MARCA todavía no admite 5 caracteres. Ejecute primero el script 07.', 1;

    IF NULLIF(LTRIM(RTRIM(@CODIGO_EMPRESA)), '') IS NULL
       OR NULLIF(LTRIM(RTRIM(@RAZON_SOCIAL)), '') IS NULL
        THROW 51032, 'Código de empresa y razón social son obligatorios.', 1;

    IF @ACTIVAR = 1
       AND
       (
           NULLIF(LTRIM(RTRIM(@FTP_RUTA_MAESTROS)), '') IS NULL
           OR NULLIF(LTRIM(RTRIM(@FTP_ARCHIVO_PRODUCTOS)), '') IS NULL
           OR EXISTS
           (
               SELECT 1
               FROM @MARCAS
               WHERE NULLIF(LTRIM(RTRIM(FTP_RUTA_ALTAS)), '') IS NULL
                  OR NULLIF(LTRIM(RTRIM(FTP_ARCHIVO_PRODUCTOS)), '') IS NULL
                  OR NULLIF(LTRIM(RTRIM(FTP_ARCHIVO_MODELOS)), '') IS NULL
                  OR NULLIF(LTRIM(RTRIM(FTP_ARCHIVO_PRIMERAS_SEGUNDAS)), '') IS NULL
                  OR NULLIF(LTRIM(RTRIM(FTP_ARCHIVO_RELFORMU)), '') IS NULL
                  OR NULLIF(LTRIM(RTRIM(FTP_ARCHIVO_RELACION)), '') IS NULL
                  OR NULLIF(LTRIM(RTRIM(RUTA_PEDIDO_EXCEL)), '') IS NULL
                  OR NULLIF(LTRIM(RTRIM(RUTA_MASTER_DATA_APP)), '') IS NULL
                  OR NULLIF(LTRIM(RTRIM(RUTA_PREC_FOB)), '') IS NULL
           )
       )
        THROW 51033, 'No se puede activar una empresa con configuración FTP incompleta.', 1;

    SELECT @ID_EMPRESA = ID_EMPRESA
    FROM dbo.EMPRESAS WITH (UPDLOCK, HOLDLOCK)
    WHERE CODIGO_EMPRESA = @CODIGO_EMPRESA;

    IF @ID_EMPRESA IS NOT NULL
       AND EXISTS
       (
           SELECT 1
           FROM dbo.EMPRESAS
           WHERE ID_EMPRESA = @ID_EMPRESA
             AND UPPER(LTRIM(RTRIM(RAZON_SOCIAL))) <>
                 UPPER(LTRIM(RTRIM(@RAZON_SOCIAL)))
       )
        THROW 51031, 'El código de empresa ya pertenece a otra razón social.', 1;

    IF @ID_EMPRESA IS NULL
    BEGIN
        INSERT INTO dbo.EMPRESAS
        (
            CODIGO_EMPRESA,
            RAZON_SOCIAL,
            ACTIVA
        )
        VALUES
        (
            @CODIGO_EMPRESA,
            @RAZON_SOCIAL,
            @ACTIVAR
        );

        SET @ID_EMPRESA = CONVERT(INT, SCOPE_IDENTITY());
    END
    ELSE
    BEGIN
        UPDATE dbo.EMPRESAS
        SET RAZON_SOCIAL = @RAZON_SOCIAL,
            ACTIVA = @ACTIVAR
        WHERE ID_EMPRESA = @ID_EMPRESA;
    END;

    /* Configuración general de maestros y productos ERP. */
    UPDATE dbo.EMPRESAS_CONFIG
    SET FTP_RUTA_MAESTROS = @FTP_RUTA_MAESTROS,
        FTP_ARCHIVO_PRODUCTOS = @FTP_ARCHIVO_PRODUCTOS,
        ACTIVA = @ACTIVAR,
        FECHA_ACTUALIZACION = SYSDATETIME()
    WHERE ID_EMPRESA = @ID_EMPRESA;

    IF @@ROWCOUNT = 0
    BEGIN
        INSERT INTO dbo.EMPRESAS_CONFIG
        (
            ID_EMPRESA,
            FTP_RUTA_MAESTROS,
            FTP_ARCHIVO_PRODUCTOS,
            ACTIVA
        )
        VALUES
        (
            @ID_EMPRESA,
            @FTP_RUTA_MAESTROS,
            @FTP_ARCHIVO_PRODUCTOS,
            @ACTIVAR
        );
    END;

    /* Maestro de marcas. */
    UPDATE MM
    SET MM.DETALLE_MARCA = M.DETALLE_MARCA,
        MM.OBSERVACION = 'Alta base BAGUNZA',
        MM.ACTIVO = @ACTIVAR,
        MM.FECHA_ACTUALIZACION = SYSDATETIME()
    FROM dbo.MAESTRO_MARCAS MM
    INNER JOIN @MARCAS M
        ON M.CODIGO_MARCA = MM.CODIGO_MARCA
    WHERE MM.ID_EMPRESA = @ID_EMPRESA;

    INSERT INTO dbo.MAESTRO_MARCAS
    (
        ID_EMPRESA,
        CODIGO_MARCA,
        DETALLE_MARCA,
        OBSERVACION,
        ACTIVO
    )
    SELECT
        @ID_EMPRESA,
        M.CODIGO_MARCA,
        M.DETALLE_MARCA,
        'Alta base BAGUNZA',
        @ACTIVAR
    FROM @MARCAS M
    WHERE NOT EXISTS
    (
        SELECT 1
        FROM dbo.MAESTRO_MARCAS MM
        WHERE MM.ID_EMPRESA = @ID_EMPRESA
          AND MM.CODIGO_MARCA = M.CODIGO_MARCA
    );

    /* Relación empresa/marca. */
    UPDATE EM
    SET EM.ACTIVA = @ACTIVAR
    FROM dbo.EMPRESAS_MARCAS EM
    INNER JOIN @MARCAS M
        ON M.CODIGO_MARCA = EM.CODIGO_MARCA
    WHERE EM.ID_EMPRESA = @ID_EMPRESA;

    INSERT INTO dbo.EMPRESAS_MARCAS
    (
        ID_EMPRESA,
        CODIGO_MARCA,
        ACTIVA
    )
    SELECT
        @ID_EMPRESA,
        M.CODIGO_MARCA,
        @ACTIVAR
    FROM @MARCAS M
    WHERE NOT EXISTS
    (
        SELECT 1
        FROM dbo.EMPRESAS_MARCAS EM
        WHERE EM.ID_EMPRESA = @ID_EMPRESA
          AND EM.CODIGO_MARCA = M.CODIGO_MARCA
    );

    /* Todos los rubros habilitados. */
    UPDATE MR
    SET MR.DETALLE_RUBRO = R.DETALLE_RUBRO,
        MR.ACTIVO = @ACTIVAR,
        MR.FECHA_ACTUALIZACION = SYSDATETIME()
    FROM dbo.MAESTRO_RUBROS MR
    INNER JOIN @RUBROS R
        ON R.CODIGO_RUBRO = MR.CODIGO_RUBRO
    WHERE MR.ID_EMPRESA = @ID_EMPRESA;

    INSERT INTO dbo.MAESTRO_RUBROS
    (
        ID_EMPRESA,
        CODIGO_RUBRO,
        DETALLE_RUBRO,
        ACTIVO
    )
    SELECT
        @ID_EMPRESA,
        R.CODIGO_RUBRO,
        R.DETALLE_RUBRO,
        @ACTIVAR
    FROM @RUBROS R
    WHERE NOT EXISTS
    (
        SELECT 1
        FROM dbo.MAESTRO_RUBROS MR
        WHERE MR.ID_EMPRESA = @ID_EMPRESA
          AND MR.CODIGO_RUBRO = R.CODIGO_RUBRO
    );

    /* Destinos de Altas por marca. */
    UPDATE C
    SET C.FTP_RUTA_EXPORTACION = M.FTP_RUTA_ALTAS,
        C.FTP_ARCHIVO_PRODUCTOS = M.FTP_ARCHIVO_PRODUCTOS,
        C.FTP_ARCHIVO_MODELOS = M.FTP_ARCHIVO_MODELOS,
        C.FTP_ARCHIVO_PRIMERAS_SEGUNDAS = M.FTP_ARCHIVO_PRIMERAS_SEGUNDAS,
        C.FTP_ARCHIVO_RELFORMU = M.FTP_ARCHIVO_RELFORMU,
        C.FTP_ARCHIVO_RELACION = M.FTP_ARCHIVO_RELACION,
        C.ACTIVA = @ACTIVAR,
        C.FECHA_ACTUALIZACION = SYSDATETIME()
    FROM dbo.EMPRESAS_MARCAS_EXPORT_CONFIG C
    INNER JOIN dbo.EMPRESAS_MARCAS EM
        ON EM.ID_EMPRESA_MARCA = C.ID_EMPRESA_MARCA
    INNER JOIN @MARCAS M
        ON M.CODIGO_MARCA = EM.CODIGO_MARCA
    WHERE EM.ID_EMPRESA = @ID_EMPRESA;

    INSERT INTO dbo.EMPRESAS_MARCAS_EXPORT_CONFIG
    (
        ID_EMPRESA_MARCA,
        FTP_RUTA_EXPORTACION,
        FTP_ARCHIVO_PRODUCTOS,
        FTP_ARCHIVO_MODELOS,
        FTP_ARCHIVO_PRIMERAS_SEGUNDAS,
        FTP_ARCHIVO_RELFORMU,
        FTP_ARCHIVO_RELACION,
        ACTIVA
    )
    SELECT
        EM.ID_EMPRESA_MARCA,
        M.FTP_RUTA_ALTAS,
        M.FTP_ARCHIVO_PRODUCTOS,
        M.FTP_ARCHIVO_MODELOS,
        M.FTP_ARCHIVO_PRIMERAS_SEGUNDAS,
        M.FTP_ARCHIVO_RELFORMU,
        M.FTP_ARCHIVO_RELACION,
        @ACTIVAR
    FROM dbo.EMPRESAS_MARCAS EM
    INNER JOIN @MARCAS M
        ON M.CODIGO_MARCA = EM.CODIGO_MARCA
    WHERE EM.ID_EMPRESA = @ID_EMPRESA
      AND NOT EXISTS
      (
          SELECT 1
          FROM dbo.EMPRESAS_MARCAS_EXPORT_CONFIG C
          WHERE C.ID_EMPRESA_MARCA = EM.ID_EMPRESA_MARCA
      );

    /* Destinos de Pedidos por marca. */
    UPDATE C
    SET C.RUTA_PEDIDO_EXCEL = M.RUTA_PEDIDO_EXCEL,
        C.RUTA_MASTER_DATA_APP = M.RUTA_MASTER_DATA_APP,
        C.RUTA_PREC_FOB = M.RUTA_PREC_FOB,
        C.ACTIVA = @ACTIVAR,
        C.FECHA_ACTUALIZACION = SYSDATETIME()
    FROM dbo.PEDIDOS_EXPORT_CONFIG C
    INNER JOIN dbo.EMPRESAS_MARCAS EM
        ON EM.ID_EMPRESA_MARCA = C.ID_EMPRESA_MARCA
    INNER JOIN @MARCAS M
        ON M.CODIGO_MARCA = EM.CODIGO_MARCA
    WHERE EM.ID_EMPRESA = @ID_EMPRESA;

    INSERT INTO dbo.PEDIDOS_EXPORT_CONFIG
    (
        ID_EMPRESA_MARCA,
        RUTA_PEDIDO_EXCEL,
        RUTA_MASTER_DATA_APP,
        RUTA_PREC_FOB,
        ACTIVA
    )
    SELECT
        EM.ID_EMPRESA_MARCA,
        M.RUTA_PEDIDO_EXCEL,
        M.RUTA_MASTER_DATA_APP,
        M.RUTA_PREC_FOB,
        @ACTIVAR
    FROM dbo.EMPRESAS_MARCAS EM
    INNER JOIN @MARCAS M
        ON M.CODIGO_MARCA = EM.CODIGO_MARCA
    WHERE EM.ID_EMPRESA = @ID_EMPRESA
      AND NOT EXISTS
      (
          SELECT 1
          FROM dbo.PEDIDOS_EXPORT_CONFIG C
          WHERE C.ID_EMPRESA_MARCA = EM.ID_EMPRESA_MARCA
      );

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    THROW;
END CATCH;

/* Diagnóstico final: empresa, marca y configuraciones. */
SELECT
    E.ID_EMPRESA,
    E.CODIGO_EMPRESA,
    E.RAZON_SOCIAL,
    E.ACTIVA AS EMPRESA_ACTIVA,
    EC.FTP_RUTA_MAESTROS,
    EC.FTP_ARCHIVO_PRODUCTOS,
    EM.ID_EMPRESA_MARCA,
    EM.CODIGO_MARCA,
    MM.DETALLE_MARCA,
    EM.ACTIVA AS MARCA_ACTIVA,
    AC.FTP_RUTA_EXPORTACION AS RUTA_ALTAS,
    AC.ACTIVA AS ALTAS_ACTIVAS,
    PC.RUTA_PEDIDO_EXCEL,
    PC.RUTA_MASTER_DATA_APP,
    PC.RUTA_PREC_FOB,
    PC.ACTIVA AS PEDIDOS_ACTIVOS
FROM dbo.EMPRESAS E
INNER JOIN dbo.EMPRESAS_CONFIG EC
    ON EC.ID_EMPRESA = E.ID_EMPRESA
INNER JOIN dbo.EMPRESAS_MARCAS EM
    ON EM.ID_EMPRESA = E.ID_EMPRESA
INNER JOIN dbo.MAESTRO_MARCAS MM
    ON MM.ID_EMPRESA = EM.ID_EMPRESA
   AND MM.CODIGO_MARCA = EM.CODIGO_MARCA
INNER JOIN dbo.EMPRESAS_MARCAS_EXPORT_CONFIG AC
    ON AC.ID_EMPRESA_MARCA = EM.ID_EMPRESA_MARCA
INNER JOIN dbo.PEDIDOS_EXPORT_CONFIG PC
    ON PC.ID_EMPRESA_MARCA = EM.ID_EMPRESA_MARCA
WHERE E.CODIGO_EMPRESA = @CODIGO_EMPRESA;

/* Diagnóstico final: ocho rubros activos. */
SELECT
    ID_EMPRESA,
    CODIGO_RUBRO,
    DETALLE_RUBRO,
    ACTIVO
FROM dbo.MAESTRO_RUBROS
WHERE ID_EMPRESA = @ID_EMPRESA
ORDER BY CODIGO_RUBRO;
