SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF OBJECT_ID('dbo.PEDIDOS_ALTAS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PEDIDOS_ALTAS
    (
        ID_EMPRESA INT NOT NULL,
        ID_PEDIDO BIGINT NOT NULL,
        ID_ALTA INT NOT NULL,
        FECHA_CREACION DATETIME2(7) NOT NULL
            CONSTRAINT DF_PEDIDOS_ALTAS_FECHA DEFAULT SYSDATETIME(),
        CONSTRAINT PK_PEDIDOS_ALTAS
            PRIMARY KEY (ID_EMPRESA, ID_PEDIDO, ID_ALTA),
        CONSTRAINT FK_PEDIDOS_ALTAS_PEDIDO
            FOREIGN KEY (ID_EMPRESA, ID_PEDIDO)
            REFERENCES dbo.PEDIDOS (ID_EMPRESA, ID_PEDIDO),
        CONSTRAINT FK_PEDIDOS_ALTAS_ALTA
            FOREIGN KEY (ID_EMPRESA, ID_ALTA)
            REFERENCES dbo.ALTAS_PRODUCTOS (ID_EMPRESA, ID_ALTA)
    );
END;

INSERT INTO dbo.PEDIDOS_ALTAS (ID_EMPRESA, ID_PEDIDO, ID_ALTA)
SELECT P.ID_EMPRESA, P.ID_PEDIDO, P.ID_ALTA
FROM dbo.PEDIDOS P
WHERE P.ID_ALTA IS NOT NULL
  AND NOT EXISTS
  (
      SELECT 1
      FROM dbo.PEDIDOS_ALTAS PA
      WHERE PA.ID_EMPRESA = P.ID_EMPRESA
        AND PA.ID_PEDIDO = P.ID_PEDIDO
        AND PA.ID_ALTA = P.ID_ALTA
  );

IF COL_LENGTH('dbo.PEDIDOS_DETALLE', 'ID_ALTA') IS NULL
BEGIN
    ALTER TABLE dbo.PEDIDOS_DETALLE ADD ID_ALTA INT NULL;
END;

EXEC sys.sp_executesql N'
    UPDATE PD
    SET PD.ID_ALTA = P.ID_ALTA
    FROM dbo.PEDIDOS_DETALLE PD
    INNER JOIN dbo.PEDIDOS P
        ON P.ID_EMPRESA = PD.ID_EMPRESA
       AND P.ID_PEDIDO = PD.ID_PEDIDO
    WHERE PD.ID_ALTA IS NULL;
';

IF NOT EXISTS
(
    SELECT 1 FROM sys.foreign_keys
    WHERE name = 'FK_PEDIDOS_DETALLE_ALTA_EMPRESA'
)
BEGIN
    EXEC sys.sp_executesql N'
        ALTER TABLE dbo.PEDIDOS_DETALLE WITH CHECK
        ADD CONSTRAINT FK_PEDIDOS_DETALLE_ALTA_EMPRESA
            FOREIGN KEY (ID_EMPRESA, ID_ALTA)
            REFERENCES dbo.ALTAS_PRODUCTOS (ID_EMPRESA, ID_ALTA);
    ';
END;

COMMIT TRANSACTION;

EXEC sys.sp_executesql N'
    SELECT
        (SELECT COUNT(*) FROM dbo.PEDIDOS_ALTAS) AS RELACIONES_PEDIDO_ALTA,
        (SELECT COUNT(*) FROM dbo.PEDIDOS_DETALLE WHERE ID_ALTA IS NULL) AS DETALLES_SIN_ALTA;
';
