SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF COL_LENGTH('dbo.MAESTRO_PAISES', 'PAIS_EAN') IS NULL
    BEGIN
        ALTER TABLE dbo.MAESTRO_PAISES
        ADD PAIS_EAN VARCHAR(3) NULL;
    END;

    IF COL_LENGTH('dbo.STG_MAESTRO_PAISES', 'PAIS_EAN') IS NULL
    BEGIN
        ALTER TABLE dbo.STG_MAESTRO_PAISES
        ADD PAIS_EAN VARCHAR(3) NULL;
    END;

    COMMIT TRANSACTION;

    SELECT
        'CONFIGURACION_OK' AS RESULTADO,
        COL_LENGTH('dbo.MAESTRO_PAISES', 'PAIS_EAN') AS LARGO_MAESTRO,
        COL_LENGTH('dbo.STG_MAESTRO_PAISES', 'PAIS_EAN') AS LARGO_STAGING;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
