SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF OBJECT_ID('dbo.GS1_PRODUCTOS_URLS', 'U') IS NULL
    BEGIN
        CREATE TABLE dbo.GS1_PRODUCTOS_URLS
        (
            ID_GS1_PRODUCTO_URL BIGINT IDENTITY(1,1) NOT NULL,
            ID_EMPRESA INT NOT NULL,
            ID_ALTA INT NOT NULL,
            COD_ALFA VARCHAR(30) NOT NULL,
            NOMBRE_IMAGEN VARCHAR(260) NOT NULL,
            URL_IMAGEN VARCHAR(2000) NOT NULL,
            USUARIO_CREACION VARCHAR(100) NOT NULL,
            FECHA_CREACION DATETIME2(7) NOT NULL
                CONSTRAINT DF_GS1_PRODUCTOS_URLS_CREACION DEFAULT SYSDATETIME(),
            USUARIO_ACTUALIZACION VARCHAR(100) NULL,
            FECHA_ACTUALIZACION DATETIME2(7) NULL,
            CONSTRAINT PK_GS1_PRODUCTOS_URLS
                PRIMARY KEY (ID_GS1_PRODUCTO_URL),
            CONSTRAINT UQ_GS1_PRODUCTOS_URLS_PRODUCTO
                UNIQUE (ID_EMPRESA, ID_ALTA, COD_ALFA),
            CONSTRAINT FK_GS1_PRODUCTOS_URLS_ALTA
                FOREIGN KEY (ID_EMPRESA, ID_ALTA)
                REFERENCES dbo.ALTAS_PRODUCTOS (ID_EMPRESA, ID_ALTA)
        );

        CREATE INDEX IX_GS1_PRODUCTOS_URLS_IMAGEN
            ON dbo.GS1_PRODUCTOS_URLS (ID_EMPRESA, NOMBRE_IMAGEN);
    END;

    COMMIT TRANSACTION;

    SELECT
        'CONFIGURACION_OK' AS RESULTADO,
        COUNT_BIG(*) AS URLS_REGISTRADAS
    FROM dbo.GS1_PRODUCTOS_URLS;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
