SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRY
    BEGIN TRANSACTION;
    IF OBJECT_ID('dbo.GS1_PRODUCTOS_EAN', 'U') IS NULL
    BEGIN
        CREATE TABLE dbo.GS1_PRODUCTOS_EAN
        (
            ID_GS1_PRODUCTO_EAN BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
            ID_EMPRESA INT NOT NULL,
            ID_ALTA INT NOT NULL,
            COD_ALFA VARCHAR(30) NOT NULL,
            EAN_GS1 VARCHAR(14) NOT NULL,
            ARCHIVO_ORIGEN VARCHAR(260) NOT NULL,
            USUARIO_CREACION VARCHAR(100) NOT NULL,
            FECHA_CREACION DATETIME2(7) NOT NULL CONSTRAINT DF_GS1_EAN_CREACION DEFAULT SYSDATETIME(),
            USUARIO_ACTUALIZACION VARCHAR(100) NULL,
            FECHA_ACTUALIZACION DATETIME2(7) NULL,
            CONSTRAINT UQ_GS1_PRODUCTOS_EAN_PRODUCTO UNIQUE (ID_EMPRESA, ID_ALTA, COD_ALFA),
            CONSTRAINT UQ_GS1_PRODUCTOS_EAN_CODIGO UNIQUE (ID_EMPRESA, EAN_GS1),
            CONSTRAINT FK_GS1_PRODUCTOS_EAN_ALTA FOREIGN KEY (ID_EMPRESA, ID_ALTA)
                REFERENCES dbo.ALTAS_PRODUCTOS (ID_EMPRESA, ID_ALTA)
        );
    END;

    IF COL_LENGTH('dbo.GS1_PRODUCTOS_EAN', 'FECHA_ENVIO_PRESEA') IS NULL
        ALTER TABLE dbo.GS1_PRODUCTOS_EAN ADD FECHA_ENVIO_PRESEA DATETIME2(7) NULL;
    IF COL_LENGTH('dbo.GS1_PRODUCTOS_EAN', 'USUARIO_ENVIO_PRESEA') IS NULL
        ALTER TABLE dbo.GS1_PRODUCTOS_EAN ADD USUARIO_ENVIO_PRESEA VARCHAR(100) NULL;
    COMMIT TRANSACTION;
    SELECT 'CONFIGURACION_OK' AS RESULTADO, COUNT_BIG(*) AS EAN_REGISTRADOS
    FROM dbo.GS1_PRODUCTOS_EAN;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
