SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

DECLARE @CONFIGURACIONES_ACTUALIZADAS INT;

UPDATE C
SET C.FTP_RUTA_EXPORTACION = '/ALTAS_PRODUCTOS/VICBOR/ATOMIK'
FROM dbo.EMPRESAS_MARCAS_EXPORT_CONFIG AS C
INNER JOIN dbo.EMPRESAS_MARCAS AS EM
    ON EM.ID_EMPRESA_MARCA = C.ID_EMPRESA_MARCA
INNER JOIN dbo.EMPRESAS AS E
    ON E.ID_EMPRESA = EM.ID_EMPRESA
WHERE UPPER(LTRIM(RTRIM(E.RAZON_SOCIAL))) = 'VICBOR'
  AND EM.CODIGO_MARCA = '1'
  AND EM.ACTIVA = 1
  AND C.ACTIVA = 1;

SET @CONFIGURACIONES_ACTUALIZADAS = @@ROWCOUNT;

IF @CONFIGURACIONES_ACTUALIZADAS <> 1
BEGIN
    ROLLBACK TRANSACTION;
    THROW 51001, 'Se esperaba actualizar una única configuración activa de VICBOR / ATOMIK.', 1;
END;

COMMIT TRANSACTION;

SELECT
    'CONFIGURACION_OK' AS RESULTADO,
    E.RAZON_SOCIAL AS EMPRESA,
    EM.CODIGO_MARCA,
    C.FTP_RUTA_EXPORTACION
FROM dbo.EMPRESAS_MARCAS_EXPORT_CONFIG AS C
INNER JOIN dbo.EMPRESAS_MARCAS AS EM
    ON EM.ID_EMPRESA_MARCA = C.ID_EMPRESA_MARCA
INNER JOIN dbo.EMPRESAS AS E
    ON E.ID_EMPRESA = EM.ID_EMPRESA
WHERE UPPER(LTRIM(RTRIM(E.RAZON_SOCIAL))) = 'VICBOR'
  AND EM.CODIGO_MARCA = '1'
  AND EM.ACTIVA = 1
  AND C.ACTIVA = 1;
