SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF OBJECT_ID('dbo.ALTAS_PRODUCTOS_IMAGENES', 'U') IS NULL
    BEGIN
        CREATE TABLE dbo.ALTAS_PRODUCTOS_IMAGENES
        (
            ID_IMAGEN BIGINT IDENTITY(1,1) NOT NULL,
            ID_EMPRESA INT NOT NULL,
            ID_ALTA INT NOT NULL,
            CODIGO_MODELO VARCHAR(30) NOT NULL,
            CODIGO_COLOR VARCHAR(30) NOT NULL,
            NOMBRE_ARCHIVO VARCHAR(260) NOT NULL,
            NOMBRE_ORIGINAL VARCHAR(260) NULL,
            EXTENSION VARCHAR(10) NOT NULL,
            RUTA_RELATIVA VARCHAR(1000) NOT NULL,
            USUARIO_CREACION VARCHAR(100) NOT NULL,
            FECHA_CREACION DATETIME2(7) NOT NULL
                CONSTRAINT DF_ALTAS_PRODUCTOS_IMAGENES_CREACION DEFAULT SYSDATETIME(),
            USUARIO_ACTUALIZACION VARCHAR(100) NULL,
            FECHA_ACTUALIZACION DATETIME2(7) NULL,
            CONSTRAINT PK_ALTAS_PRODUCTOS_IMAGENES PRIMARY KEY (ID_IMAGEN),
            CONSTRAINT UQ_ALTAS_PRODUCTOS_IMAGENES_FAMILIA
                UNIQUE (ID_EMPRESA, ID_ALTA, CODIGO_MODELO, CODIGO_COLOR),
            CONSTRAINT FK_ALTAS_PRODUCTOS_IMAGENES_ALTA
                FOREIGN KEY (ID_EMPRESA, ID_ALTA)
                REFERENCES dbo.ALTAS_PRODUCTOS (ID_EMPRESA, ID_ALTA)
        );

        CREATE INDEX IX_ALTAS_PRODUCTOS_IMAGENES_ALTA
            ON dbo.ALTAS_PRODUCTOS_IMAGENES (ID_EMPRESA, ID_ALTA);
    END;

    COMMIT TRANSACTION;

    SELECT
        'CONFIGURACION_OK' AS RESULTADO,
        COUNT_BIG(*) AS IMAGENES_REGISTRADAS
    FROM dbo.ALTAS_PRODUCTOS_IMAGENES;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
