SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

IF OBJECT_ID('dbo.ALTAS_MAESTROS_CONFIGURACION', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ALTAS_MAESTROS_CONFIGURACION (
        ID_EMPRESA INT NOT NULL PRIMARY KEY,
        RUTA_DESTINO VARCHAR(500) NOT NULL,
        ACTIVO BIT NOT NULL CONSTRAINT DF_AMC_ACTIVO DEFAULT (1),
        FECHA_ACTUALIZACION DATETIME2(0) NOT NULL CONSTRAINT DF_AMC_FECHA DEFAULT (SYSDATETIME()),
        CONSTRAINT FK_AMC_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES dbo.EMPRESAS(ID_EMPRESA)
    );
END;

IF OBJECT_ID('dbo.ALTAS_MAESTROS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ALTAS_MAESTROS (
        ID_ALTA_MAESTRO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ID_EMPRESA INT NOT NULL,
        TIPO VARCHAR(20) NOT NULL,
        CODIGO VARCHAR(20) NOT NULL,
        NOMBRE VARCHAR(100) NOT NULL,
        C_PROVEEDO VARCHAR(50) NULL,
        LICENCIA VARCHAR(20) NULL,
        MARCA VARCHAR(20) NULL,
        RUBRO VARCHAR(20) NULL,
        DATOS_JSON NVARCHAR(MAX) NULL,
        ESTADO VARCHAR(25) NOT NULL CONSTRAINT DF_AM_ESTADO DEFAULT ('BORRADOR'),
        ARCHIVO_DBI VARCHAR(100) NULL,
        USUARIO_CREACION VARCHAR(100) NOT NULL,
        FECHA_CREACION DATETIME2(0) NOT NULL CONSTRAINT DF_AM_FECHA DEFAULT (SYSDATETIME()),
        USUARIO_ENVIO VARCHAR(100) NULL,
        FECHA_ENVIO DATETIME2(0) NULL,
        FECHA_CONFIRMACION_ERP DATETIME2(0) NULL,
        CONSTRAINT FK_AM_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES dbo.EMPRESAS(ID_EMPRESA),
        CONSTRAINT CK_AM_TIPO CHECK (TIPO IN ('COLOR', 'MODELO', 'MODULO')),
        CONSTRAINT CK_AM_ESTADO CHECK (ESTADO IN ('BORRADOR', 'PENDIENTE_ENVIO', 'ENVIADO_PRESEA', 'CONFIRMADO_ERP', 'ANULADO')),
        CONSTRAINT CK_AM_JSON CHECK (DATOS_JSON IS NULL OR ISJSON(DATOS_JSON) = 1),
        CONSTRAINT UQ_AM_CODIGO UNIQUE (ID_EMPRESA, TIPO, CODIGO)
    );
    CREATE INDEX IX_AM_EMPRESA_ESTADO ON dbo.ALTAS_MAESTROS(ID_EMPRESA, ESTADO, TIPO);
END;

IF OBJECT_ID('dbo.ALTAS_MAESTROS_HISTORIAL', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ALTAS_MAESTROS_HISTORIAL (
        ID_HISTORIAL BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ID_ALTA_MAESTRO INT NOT NULL,
        ESTADO_ANTERIOR VARCHAR(25) NULL,
        ESTADO_NUEVO VARCHAR(25) NOT NULL,
        OBSERVACION VARCHAR(500) NULL,
        USUARIO VARCHAR(100) NOT NULL,
        FECHA DATETIME2(0) NOT NULL CONSTRAINT DF_AMH_FECHA DEFAULT (SYSDATETIME()),
        CONSTRAINT FK_AMH_ALTA FOREIGN KEY (ID_ALTA_MAESTRO) REFERENCES dbo.ALTAS_MAESTROS(ID_ALTA_MAESTRO)
    );
END;

;WITH RUTAS AS (
    SELECT 'VICBOR' EMPRESA, '\\ftpserver02\ftpvicbor\ALTAS_MAESTROS\VICBOR' RUTA UNION ALL
    SELECT 'MIDING', '\\ftpserver02\ftpvicbor\ALTAS_MAESTROS\MIDING' UNION ALL
    SELECT 'INDUSTRIAS GYD', '\\ftpserver02\ftpvicbor\ALTAS_MAESTROS\GYD' UNION ALL
    SELECT 'BAGUNZA', '\\ftpserver02\ftpvicbor\ALTAS_MAESTROS\BAGUNZA'
)
MERGE dbo.ALTAS_MAESTROS_CONFIGURACION D
USING (
    SELECT E.ID_EMPRESA, R.RUTA
    FROM dbo.EMPRESAS E INNER JOIN RUTAS R ON UPPER(LTRIM(RTRIM(E.RAZON_SOCIAL))) = R.EMPRESA
) O ON D.ID_EMPRESA = O.ID_EMPRESA
WHEN MATCHED THEN UPDATE SET RUTA_DESTINO = O.RUTA, ACTIVO = 1, FECHA_ACTUALIZACION = SYSDATETIME()
WHEN NOT MATCHED THEN INSERT (ID_EMPRESA, RUTA_DESTINO) VALUES (O.ID_EMPRESA, O.RUTA);

COMMIT;

SELECT 'CONFIGURACION_OK' RESULTADO, COUNT(*) EMPRESAS_CONFIGURADAS
FROM dbo.ALTAS_MAESTROS_CONFIGURACION WHERE ACTIVO = 1;
