SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

;WITH RUTAS AS (
    SELECT 'VICBOR' EMPRESA, '/ALTAS_MAESTROS/VICBOR' RUTA UNION ALL
    SELECT 'MIDING', '/ALTAS_MAESTROS/MIDING' UNION ALL
    SELECT 'INDUSTRIAS GYD', '/ALTAS_MAESTROS/GYD' UNION ALL
    SELECT 'BAGUNZA', '/ALTAS_MAESTROS/BAGUNZA'
)
UPDATE C
SET C.RUTA_DESTINO = R.RUTA,
    C.FECHA_ACTUALIZACION = SYSDATETIME()
FROM dbo.ALTAS_MAESTROS_CONFIGURACION C
INNER JOIN dbo.EMPRESAS E ON E.ID_EMPRESA = C.ID_EMPRESA
INNER JOIN RUTAS R ON UPPER(LTRIM(RTRIM(E.RAZON_SOCIAL))) = R.EMPRESA;

COMMIT;

SELECT E.RAZON_SOCIAL, C.RUTA_DESTINO, C.ACTIVO
FROM dbo.ALTAS_MAESTROS_CONFIGURACION C
INNER JOIN dbo.EMPRESAS E ON E.ID_EMPRESA = C.ID_EMPRESA
ORDER BY C.ID_EMPRESA;
