SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

/*
 * FTP usa "/" como separador. Todas las rutas completas quedan absolutas
 * para que no dependan de la carpeta inicial de la sesión FTP.
 */
UPDATE C
SET C.FTP_RUTA_EXPORTACION =
    '/' + LTRIM(
        REPLACE(LTRIM(RTRIM(C.FTP_RUTA_EXPORTACION)), '\', '/'),
        '/'
    )
FROM dbo.EMPRESAS_MARCAS_EXPORT_CONFIG AS C
WHERE NULLIF(LTRIM(RTRIM(C.FTP_RUTA_EXPORTACION)), '') IS NOT NULL;

/* Corrige configuraciones históricas donde BAGUNZA quedó duplicado. */
UPDATE C
SET C.FTP_RUTA_EXPORTACION = '/ALTAS_PRODUCTOS/BAGUNZA'
FROM dbo.EMPRESAS_MARCAS_EXPORT_CONFIG AS C
WHERE UPPER(C.FTP_RUTA_EXPORTACION) = '/ALTAS_PRODUCTOS/BAGUNZA/BAGUNZA';

/*
 * Una configuración reservada para una empresa futura no debe participar
 * de las exportaciones hasta tener ruta y todos sus nombres de archivo.
 */
UPDATE C
SET C.ACTIVA = 0
FROM dbo.EMPRESAS_MARCAS_EXPORT_CONFIG AS C
WHERE C.ACTIVA = 1
  AND (
      NULLIF(LTRIM(RTRIM(C.FTP_RUTA_EXPORTACION)), '') IS NULL
      OR NULLIF(LTRIM(RTRIM(C.FTP_ARCHIVO_PRODUCTOS)), '') IS NULL
      OR NULLIF(LTRIM(RTRIM(C.FTP_ARCHIVO_MODELOS)), '') IS NULL
      OR NULLIF(LTRIM(RTRIM(C.FTP_ARCHIVO_PRIMERAS_SEGUNDAS)), '') IS NULL
      OR NULLIF(LTRIM(RTRIM(C.FTP_ARCHIVO_RELFORMU)), '') IS NULL
      OR NULLIF(LTRIM(RTRIM(C.FTP_ARCHIVO_RELACION)), '') IS NULL
  );

COMMIT TRANSACTION;

SELECT
    C.ID_EMPRESA_MARCA,
    C.FTP_RUTA_EXPORTACION,
    C.ACTIVA
FROM dbo.EMPRESAS_MARCAS_EXPORT_CONFIG AS C
ORDER BY C.ID_EMPRESA_MARCA;
