SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

IF COL_LENGTH('dbo.MAESTRO_MODELOS', 'C_PROVEEDO') IS NULL
BEGIN
    ALTER TABLE dbo.MAESTRO_MODELOS
        ADD C_PROVEEDO VARCHAR(20) NULL;
END;

IF COL_LENGTH('dbo.MAESTRO_MODELOS', 'C_PROVEEDO') < 20
BEGIN
    ALTER TABLE dbo.MAESTRO_MODELOS
        ALTER COLUMN C_PROVEEDO VARCHAR(20) NULL;
END;

IF OBJECT_ID('dbo.STG_MAESTRO_MODELOS', 'U') IS NOT NULL
   AND COL_LENGTH('dbo.STG_MAESTRO_MODELOS', 'C_PROVEEDO') IS NULL
BEGIN
    ALTER TABLE dbo.STG_MAESTRO_MODELOS
        ADD C_PROVEEDO VARCHAR(20) NULL;
END;

IF OBJECT_ID('dbo.STG_MAESTRO_MODELOS', 'U') IS NOT NULL
   AND COL_LENGTH('dbo.STG_MAESTRO_MODELOS', 'C_PROVEEDO') < 20
BEGIN
    ALTER TABLE dbo.STG_MAESTRO_MODELOS
        ALTER COLUMN C_PROVEEDO VARCHAR(20) NULL;
END;

COMMIT TRANSACTION;

SELECT
    COL_LENGTH('dbo.MAESTRO_MODELOS', 'C_PROVEEDO') AS LARGO_C_PROVEEDO_MODELOS,
    COL_LENGTH('dbo.STG_MAESTRO_MODELOS', 'C_PROVEEDO') AS LARGO_C_PROVEEDO_STAGING;
