/* Permiso de reportes administrable por usuario y empresa. */
IF COL_LENGTH('dbo.USUARIOS_ACCESOS', 'PUEDE_VER_REPORTES') IS NULL
BEGIN
  ALTER TABLE dbo.USUARIOS_ACCESOS
    ADD PUEDE_VER_REPORTES BIT NOT NULL
      CONSTRAINT DF_USUARIOS_ACCESOS_PUEDE_VER_REPORTES DEFAULT (0) WITH VALUES;

  EXEC(N'
    UPDATE UA
    SET PUEDE_VER_REPORTES = 1
    FROM dbo.USUARIOS_ACCESOS UA
    INNER JOIN dbo.ROLES R ON R.ID_ROL = UA.ID_ROL
    WHERE UPPER(LTRIM(RTRIM(R.CODIGO_ROL))) IN (''ADMIN'', ''CONSULTAS'', ''SUPER_ADMIN'');
  ');
END;
