IF OBJECT_ID('dbo.REGLAS_REQUERIMIENTO_EAN', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.REGLAS_REQUERIMIENTO_EAN (
    ID_REGLA_EAN INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_EMPRESA INT NOT NULL,
    MARCA VARCHAR(50) NOT NULL,
    RUBRO VARCHAR(50) NOT NULL,
    LICENCIA VARCHAR(50) NOT NULL CONSTRAINT DF_REGLA_EAN_LICENCIA DEFAULT(''),
    REQUIERE_EAN BIT NOT NULL CONSTRAINT DF_REGLA_EAN_REQUIERE DEFAULT(1),
    ACTIVO BIT NOT NULL CONSTRAINT DF_REGLA_EAN_ACTIVO DEFAULT(1),
    USUARIO_ACTUALIZACION VARCHAR(100) NOT NULL,
    FECHA_ACTUALIZACION DATETIME2 NOT NULL CONSTRAINT DF_REGLA_EAN_FECHA DEFAULT(SYSDATETIME()),
    CONSTRAINT UQ_REGLA_EAN_ALCANCE UNIQUE (ID_EMPRESA, MARCA, RUBRO, LICENCIA)
  );
END;
