SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF COL_LENGTH('dbo.PRODUCTOS', 'C_ESTADIO') IS NULL
    ALTER TABLE dbo.PRODUCTOS ADD C_ESTADIO VARCHAR(10) NULL;

IF COL_LENGTH('dbo.PRODUCTOS_ERP_STAGING', 'C_ESTADIO') IS NULL
    ALTER TABLE dbo.PRODUCTOS_ERP_STAGING ADD C_ESTADIO VARCHAR(10) NULL;

COMMIT TRANSACTION;
