IF OBJECT_ID('dbo.REGLAS_REQUERIMIENTO_EAN', 'U') IS NULL
    THROW 51060, 'Primero debe ejecutarse 25_reglas_ean.sql.', 1;

DECLARE @ID_EMPRESA INT;
SELECT TOP 1 @ID_EMPRESA = ID_EMPRESA
FROM dbo.EMPRESAS
WHERE UPPER(LTRIM(RTRIM(RAZON_SOCIAL))) IN ('GYD', 'INDUSTRIAS GYD')
   OR UPPER(LTRIM(RTRIM(CODIGO_EMPRESA))) = 'GYD';

IF @ID_EMPRESA IS NULL
    THROW 51061, 'No se encontró la empresa GYD.', 1;

MERGE dbo.REGLAS_REQUERIMIENTO_EAN AS T
USING (SELECT @ID_EMPRESA AS ID_EMPRESA, '*' AS MARCA, '*' AS RUBRO, '' AS LICENCIA) AS S
ON T.ID_EMPRESA=S.ID_EMPRESA AND T.MARCA=S.MARCA AND T.RUBRO=S.RUBRO AND T.LICENCIA=S.LICENCIA
WHEN MATCHED THEN
  UPDATE SET REQUIERE_EAN=0, ACTIVO=1, USUARIO_ACTUALIZACION='MIGRACION', FECHA_ACTUALIZACION=SYSDATETIME()
WHEN NOT MATCHED THEN
  INSERT(ID_EMPRESA,MARCA,RUBRO,LICENCIA,REQUIERE_EAN,ACTIVO,USUARIO_ACTUALIZACION)
  VALUES(@ID_EMPRESA,'*','*','',0,1,'MIGRACION');
