SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF COL_LENGTH('dbo.PEDIDOS_ALTAS', 'MODO_SELECCION') IS NULL
BEGIN
    ALTER TABLE dbo.PEDIDOS_ALTAS ADD MODO_SELECCION VARCHAR(20) NULL;
END;

EXEC sys.sp_executesql N'
    UPDATE PA
    SET MODO_SELECCION = CASE
        WHEN A.TIPO_PRODUCTO = ''MODULO'' THEN ''MODULO''
        ELSE ''PAR_SUELTO''
    END
    FROM dbo.PEDIDOS_ALTAS PA
    INNER JOIN dbo.ALTAS_PRODUCTOS A
        ON A.ID_EMPRESA = PA.ID_EMPRESA
       AND A.ID_ALTA = PA.ID_ALTA
    WHERE PA.MODO_SELECCION IS NULL;

    ALTER TABLE dbo.PEDIDOS_ALTAS
        ALTER COLUMN MODO_SELECCION VARCHAR(20) NOT NULL;
';

IF NOT EXISTS (
    SELECT 1 FROM sys.check_constraints
    WHERE name = 'CK_PEDIDOS_ALTAS_MODO_SELECCION'
)
BEGIN
    EXEC sys.sp_executesql N'
        ALTER TABLE dbo.PEDIDOS_ALTAS WITH CHECK
        ADD CONSTRAINT CK_PEDIDOS_ALTAS_MODO_SELECCION
            CHECK (MODO_SELECCION IN (''MODULO'', ''PAR_SUELTO''));
    ';
END;

COMMIT TRANSACTION;
