SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF OBJECT_ID('dbo.ALTAS_PRODUCTOS_FOTOS_ERP_ENVIOS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ALTAS_PRODUCTOS_FOTOS_ERP_ENVIOS
    (
        ID_ENVIO BIGINT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_ALTAS_PRODUCTOS_FOTOS_ERP_ENVIOS PRIMARY KEY,
        ID_EMPRESA INT NOT NULL,
        ID_ALTA INT NOT NULL,
        RUTA_DESTINO VARCHAR(1000) NOT NULL,
        CANTIDAD_COPIADAS INT NOT NULL,
        CANTIDAD_SIN_CAMBIOS INT NOT NULL,
        USUARIO_ENVIO VARCHAR(100) NOT NULL,
        FECHA_ENVIO DATETIME2(7) NOT NULL
            CONSTRAINT DF_ALTAS_PRODUCTOS_FOTOS_ERP_FECHA DEFAULT SYSDATETIME(),
        CONSTRAINT FK_ALTAS_PRODUCTOS_FOTOS_ERP_ALTA
            FOREIGN KEY (ID_EMPRESA, ID_ALTA)
            REFERENCES dbo.ALTAS_PRODUCTOS (ID_EMPRESA, ID_ALTA)
    );

    CREATE INDEX IX_ALTAS_PRODUCTOS_FOTOS_ERP_ALTA
        ON dbo.ALTAS_PRODUCTOS_FOTOS_ERP_ENVIOS (ID_EMPRESA, ID_ALTA, FECHA_ENVIO DESC);
END;

COMMIT TRANSACTION;
