SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF OBJECT_ID('dbo.PEDIDOS_CONFIRMACIONES_COMEX', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PEDIDOS_CONFIRMACIONES_COMEX
    (
        ID_CONFIRMACION_COMEX BIGINT IDENTITY(1,1) NOT NULL,
        ID_EMPRESA INT NOT NULL,
        ID_PEDIDO BIGINT NOT NULL,
        ESTADO VARCHAR(20) NOT NULL
            CONSTRAINT DF_PEDIDOS_COMEX_ESTADO DEFAULT 'CONFIRMADO',
        ORIGEN VARCHAR(20) NOT NULL
            CONSTRAINT DF_PEDIDOS_COMEX_ORIGEN DEFAULT 'MANUAL',
        FECHA_CONFIRMACION DATETIME2(7) NOT NULL
            CONSTRAINT DF_PEDIDOS_COMEX_FECHA DEFAULT SYSDATETIME(),
        USUARIO_CONFIRMACION VARCHAR(100) NOT NULL,
        RESPUESTA_EXTERNA NVARCHAR(MAX) NULL,
        CONSTRAINT PK_PEDIDOS_CONFIRMACIONES_COMEX
            PRIMARY KEY (ID_CONFIRMACION_COMEX),
        CONSTRAINT UQ_PEDIDOS_CONFIRMACIONES_COMEX_PEDIDO
            UNIQUE (ID_EMPRESA, ID_PEDIDO),
        CONSTRAINT FK_PEDIDOS_CONFIRMACIONES_COMEX_PEDIDO
            FOREIGN KEY (ID_EMPRESA, ID_PEDIDO)
            REFERENCES dbo.PEDIDOS (ID_EMPRESA, ID_PEDIDO),
        CONSTRAINT CK_PEDIDOS_CONFIRMACIONES_COMEX_ESTADO
            CHECK (ESTADO IN ('CONFIRMADO')),
        CONSTRAINT CK_PEDIDOS_CONFIRMACIONES_COMEX_ORIGEN
            CHECK (ORIGEN IN ('MANUAL', 'API'))
    );
END;

COMMIT TRANSACTION;

SELECT COUNT(*) AS CONFIRMACIONES_COMEX
FROM dbo.PEDIDOS_CONFIRMACIONES_COMEX;
