SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF OBJECT_ID('dbo.PEDIDOS_CONFIRMACIONES_PRESEA', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PEDIDOS_CONFIRMACIONES_PRESEA
    (
        ID_CONFIRMACION_PRESEA BIGINT IDENTITY(1,1) NOT NULL,
        ID_EMPRESA INT NOT NULL,
        ID_PEDIDO BIGINT NOT NULL,
        ESTADO VARCHAR(20) NOT NULL CONSTRAINT DF_PEDIDOS_PRESEA_ESTADO DEFAULT 'CONFIRMADO',
        FECHA_CONFIRMACION DATETIME2(7) NOT NULL CONSTRAINT DF_PEDIDOS_PRESEA_FECHA DEFAULT SYSDATETIME(),
        USUARIO_CONFIRMACION VARCHAR(100) NOT NULL,
        CONSTRAINT PK_PEDIDOS_CONFIRMACIONES_PRESEA PRIMARY KEY (ID_CONFIRMACION_PRESEA),
        CONSTRAINT UQ_PEDIDOS_CONFIRMACIONES_PRESEA_PEDIDO UNIQUE (ID_EMPRESA, ID_PEDIDO),
        CONSTRAINT FK_PEDIDOS_CONFIRMACIONES_PRESEA_PEDIDO FOREIGN KEY (ID_EMPRESA, ID_PEDIDO)
            REFERENCES dbo.PEDIDOS (ID_EMPRESA, ID_PEDIDO),
        CONSTRAINT CK_PEDIDOS_CONFIRMACIONES_PRESEA_ESTADO CHECK (ESTADO IN ('CONFIRMADO'))
    );
END;

COMMIT TRANSACTION;

SELECT COUNT(*) AS CONFIRMACIONES_PRESEA FROM dbo.PEDIDOS_CONFIRMACIONES_PRESEA;
