SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF OBJECT_ID('dbo.PEDIDOS_EXPORTACIONES', 'U') IS NULL
        THROW 50001, 'No existe la tabla dbo.PEDIDOS_EXPORTACIONES.', 1;

    IF EXISTS (
        SELECT 1
        FROM sys.check_constraints
        WHERE parent_object_id = OBJECT_ID('dbo.PEDIDOS_EXPORTACIONES')
          AND name = 'CK_PEDIDOS_EXPORTACIONES_TIPO'
    )
    BEGIN
        ALTER TABLE dbo.PEDIDOS_EXPORTACIONES
            DROP CONSTRAINT CK_PEDIDOS_EXPORTACIONES_TIPO;
    END;

    ALTER TABLE dbo.PEDIDOS_EXPORTACIONES WITH CHECK
        ADD CONSTRAINT CK_PEDIDOS_EXPORTACIONES_TIPO
        CHECK (TIPO_EXPORTACION IN (
            'PEDIDO_EXCEL',
            'MASTER_DATA_APP',
            'PREC_FOB',
            'PEDIDO_NACIONAL'
        ));

    ALTER TABLE dbo.PEDIDOS_EXPORTACIONES
        CHECK CONSTRAINT CK_PEDIDOS_EXPORTACIONES_TIPO;

    COMMIT TRANSACTION;

    SELECT name AS RESTRICCION, definition AS DEFINICION
    FROM sys.check_constraints
    WHERE parent_object_id = OBJECT_ID('dbo.PEDIDOS_EXPORTACIONES')
      AND name = 'CK_PEDIDOS_EXPORTACIONES_TIPO';
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
