SET NOCOUNT ON;
SET XACT_ABORT ON;

IF COL_LENGTH('dbo.USUARIOS_ACCESOS', 'PUEDE_USAR_TALLES_MIXTOS') IS NULL
BEGIN
  ALTER TABLE dbo.USUARIOS_ACCESOS
    ADD PUEDE_USAR_TALLES_MIXTOS BIT NOT NULL
      CONSTRAINT DF_USUARIOS_ACCESOS_PUEDE_USAR_TALLES_MIXTOS DEFAULT (0) WITH VALUES;
END;

EXEC sys.sp_executesql N'
  SELECT COUNT(*) AS ACCESOS_HABILITADOS
  FROM dbo.USUARIOS_ACCESOS
  WHERE PUEDE_USAR_TALLES_MIXTOS = 1;';
