SET NOCOUNT ON;
SET XACT_ABORT ON;

IF COL_LENGTH('dbo.ALTAS_PRODUCTOS_FAMILIAS_DETALLE', 'CANTIDAD') IS NULL
BEGIN
  ALTER TABLE dbo.ALTAS_PRODUCTOS_FAMILIAS_DETALLE
    ADD CANTIDAD INT NULL;
END;

IF NOT EXISTS (
  SELECT 1 FROM sys.check_constraints
  WHERE parent_object_id = OBJECT_ID('dbo.ALTAS_PRODUCTOS_FAMILIAS_DETALLE')
    AND name = 'CK_ALTAS_FAMILIAS_CANTIDAD_POSITIVA'
)
BEGIN
  EXEC sys.sp_executesql N'
    ALTER TABLE dbo.ALTAS_PRODUCTOS_FAMILIAS_DETALLE WITH CHECK
      ADD CONSTRAINT CK_ALTAS_FAMILIAS_CANTIDAD_POSITIVA
      CHECK (CANTIDAD IS NULL OR CANTIDAD > 0);';
END;

EXEC sys.sp_executesql N'
  SELECT COUNT(*) AS RELACIONES_CON_CANTIDAD
  FROM dbo.ALTAS_PRODUCTOS_FAMILIAS_DETALLE
  WHERE CANTIDAD IS NOT NULL;';
